name: Latihan 2
# Menunjukan hasil secara public, meskipun latihan 2 ini tidak finish
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install update
        run: sudo apt update -y
      - name: Install nginx
        run: sudo apt install nginx -y
      - name: Tes landing page nginx
        run: sudo systemctl start nginx
      - name: Install CLoudflare
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb -o cloudflared.deb
          sudo dpkg -i cloudflared.deb
          cloudflared --version
      - name: Jalankan Cloudflare Quick Tunnel
        run: sudo cloudflared tunnel --url http://localhost:80
